from __future__ import annotations

MODEL_FIELD_ARG_ORDER: dict[str | None, int] = {
    "verbose_name": 0,
    "name": 1,
    "primary_key": 2,
    "max_length": 3,
    "unique": 4,
    "blank": 5,
    "null": 6,
    "db_index": 7,
    "rel": 8,
    "default": 9,
    "editable": 10,
    "serialize": 11,
    "unique_for_date": 12,
    "unique_for_month": 13,
    "unique_for_year": 14,
    "choices": 15,
    "help_text": 16,
    "db_column": 17,
    "db_tablespace": 18,
    "auto_created": 19,
    "validators": 20,
    "error_messages": 21,
    "db_comment": 22,
    "db_default": 23,
    "db_collation": 24,
    "auto_now": 25,
    "auto_now_add": 26,
    "max_digits": 27,
    "decimal_places": 28,
    "path": 29,
    "match": 30,
    "recursive": 31,
    "allow_files": 32,
    "allow_folders": 33,
    "protocol": 34,
    "unpack_ipv4": 35,
    "allow_unicode": 36,
}
